services:
  litellm:
    image: docker.litellm.ai/berriai/litellm:main-stable
    ports:
      - "4002:4000"
    environment:
      DATABASE_URL: "postgresql://llmproxy:dbpassword9090@db:5432/litellm"
      LITELLM_MASTER_KEY: "sk-1234"
      STORE_MODEL_IN_DB: "True"
    volumes:
      - ./config.yaml:/app/config.yaml
    command: ["--config=/app/config.yaml", "--port", "4000"]
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: litellm-db
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: llmproxy
      POSTGRES_PASSWORD: dbpassword9090
    ports:
      - "5434:5432"
